name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем репозиторий
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0        # нужен полный history для docusaurus deploy

      # 2. Настраиваем Node и включаем кеш для npm
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm            # <-- переключили cache с yarn на npm

      # 3. Устанавливаем зависимости
      #    npm ci быстрее и использует package-lock.json
      - name: Install dependencies
        run: npm ci

      # 4. Сборка сайта
      - name: Build website
        run: npm run build

      # 5. Деплой в ветку gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cname: datacloudhero.com         # ← ваш домен без https://
          publish_dir: ./build
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
